// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // DATABASE_URL is required for migrations and CLI operations
  // The client connection uses the adapter in src/lib/db.ts
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
